workflows:
  ios-release:
    name: iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Sahifati ASC Key

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: org.sahifati.app
      groups:
        - flutter_secrets
      vars:
        FLUTTER_VERSION: stable
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --dart-define=API_BASE_URL=https://sahifati.org/api \
            --dart-define=GOOGLE_WEB_CLIENT_ID=821809289982-m9g7reu9a9vfju911rg3uqg009rr12rp.apps.googleusercontent.com \
            --dart-define=GOOGLE_SERVER_CLIENT_ID=821809289982-m9g7reu9a9vfju911rg3uqg009rr12rp.apps.googleusercontent.com \
            --dart-define=APPLE_WEB_CLIENT_ID=org.sahifati.app.signin \
            --dart-define=APPLE_REDIRECT_URI=https://sahifati.org/api/auth/social/apple/callback \
            --dart-define=FACEBOOK_AUTH_ENABLED=true \
            --dart-define=FACEBOOK_APP_ID=824178674089653 \
            --dart-define=HUAWEI_APP_ID=116918405

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Sahifati-External
